config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/weather_search', controller: :weathers, action: :search
  post '/weather_search', controller: :weathers, action: :search
  root to: 'weathers#index'
end

app/models/guest_user.rb
# frozen_string_literal: true

class GuestUser
  attr_reader :name

  def initialize
    @name = 'Guest'
  end
end

app/models/weather.rb
# frozen_string_literal: true

Weather = Struct.new(:updated_at, :temperature_in_celcius, :temperature_in_fahrenheit, keyword_init: true)

app/models/weather_report.rb
# frozen_string_literal: true

WeatherReport = Struct.new(:current, keyword_init: true)

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protected

  def current_user
    @current_user ||= GuestUser.new
  end
  helper_method :current_user
end

app/controllers/weathers_controller.rb
# frozen_string_literal: true

class WeathersController < ApplicationController
  def index; end

  # rubocop:disable Metrics/AbcSize
  def search
    address = params.require(:address)
                    .permit('city', 'state', 'country', 'zip_code')
                    .to_h.filter_map { |(_, v)| v.presence }.join(' ')

    # Here, the requirement was to cache the report by zip_code; however, we can search by other attributes
    # too. So, in order to have consistency for caching and save API calls, I am caching the api response for
    # the whole address.
    cached = Rails.cache.exist?(address)
    response = Rails.cache.fetch(address, expires_in: 30.minutes) { WeatherApi.fetch_weather_report(address:) }

    weather_component =
      if response.success?
        WeatherComponent.new(report: WeatherForecastApiFormatter.format(response.body), cached:)
      else
        NoWeatherComponent.new
      end

    render(turbo_stream: turbo_stream.update('weather-report', weather_component))
  end
  # rubocop:enable Metrics/AbcSize
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherForecast</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render(WelcomeComponent.new(user: current_user)) %>
    <%= yield %>
  </body>
</html>

app/views/weathers/index.html.erb
<%= form_tag weather_search_path do %>
  <% address_params = params[:address] || {} %>
  <%= text_field_tag 'address[city]', address_params[:city], placeholder: 'City' %>
  <%= text_field_tag 'address[state]', address_params[:state], placeholder: 'State' %>
  <%= text_field_tag 'address[country]', address_params[:country], placeholder: 'Country' %>
  <%= text_field_tag 'address[zip_code]', address_params[:zip_code], placeholder: 'Zipcode' %>
  <%= submit_tag 'Show Weather' %>
<% end %>

<%= turbo_frame_tag 'weather-report' %>